### ISSUE TITLE
VGMPlay does not produce sound for YMF278B

### ISSUE THREAD

**Issue by TulioAdriano** [ValleyBell/in_vgm-libvgm#5]
Please see file attached. in_vgm plays the file normally over Winamp.

[01_Title.zip](https://github.com/ValleyBell/in_vgm-libvgm/files/9364133/01_Title.zip)

**Comment by ValleyBell** [comment]
I ...think this is in the wrong repo?

In any case: This is probably caused by VGMPlay being unable to locate `yrw801.rom`.
It usually reports this:
```
VGM Player
----------

File Name:      R:\01_Title.vgm

Unable to find yrw801.rom!
Track Title:    Intro
Game Name:      Sonyc
```

The solution is to place the required ROM file in the same folder as VGMPlay.

**Comment by TulioAdriano** [comment]
I apologize for the wrong repo. I'll pay more attention in the future. In any case, still a mystery why does it work with in_vgm... 
Let me know if you want this re-posted for further investigation.
